### ISSUE TITLE
Thoughts on Portal Cache Test

### ISSUE THREAD

**Issue by aliyoussefi** [tyler-hogsett-microsoft/clear-portal-cache#3]
For the puppeteer code, I would like to see an approach that would remove the hard coded strings from the commands. for instance tag names, element ids, etc.

**Comment by aliyoussefi** [comment]
Can you add a label for feature on this? i can't seem to.

**Comment by tyler-hogsett-microsoft** [comment]
Thanks for the feedback, @aliyoussefi. At the time I wrote this, I couldn't find any way to authenticate with the Portal Admin API without using Puppeteer. Do you know if there is a recommended way to interact with a page without referencing tag names?

**Comment by aliyoussefi** [comment]
@tyler-hogsett-microsoft  I think it looks good, what i was referring to was to centralize the hard coded strings for the inputs in case you begin adding additional automation scripts to make it easier to update if say the control id changes. What would be interesting is to see about using XPath and puppeteer to leverage some of the query syntax for dynamic class and id names.
